server:
  port: 9192

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 403411
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: com.stu.frame.myspringboot.model
  mapperLocations: classpath:mapper/*.xml



